export const dataAnalyticsVisuals = [
  { title: "ARISE programme intelligence", category: "Population health", description: "Respondent, patient and provider indicators paired with a geographic view.", image: "https://media.base44.com/images/public/6a554b016ff6fa6eb6e63b81/9839ec244_ARISEDB.png" },
  { title: "Hospital operating picture", category: "Facility operations", description: "Department activity, bed capacity and service visibility in one view.", image: "https://media.base44.com/images/public/6a554b016ff6fa6eb6e63b81/ec4e293d5_HospitalCHIPDashboard.png" },
  { title: "Master facility intelligence", category: "Network mapping", description: "Country coverage, service locations and headline population indicators.", image: "https://media.base44.com/images/public/6a554b016ff6fa6eb6e63b81/fe528693c_IndepthMasterDB.png" },
  { title: "County revenue intelligence", category: "Public-sector analytics", description: "Revenue, trader, market and compliance views for local government teams.", image: "https://media.base44.com/images/public/6a554b016ff6fa6eb6e63b81/612618f28_KenyaCountyRevenueDB.png" },
  { title: "Health facility mapping", category: "Geospatial intelligence", description: "Facility coverage and service indicators across a connected district network.", image: "https://media.base44.com/images/public/6a554b016ff6fa6eb6e63b81/88ff6b951_Screenshot2026-07-17105349.png" },
  { title: "Laboratory network view", category: "Diagnostics", description: "Laboratory facilities, capability patterns and service readiness on the map.", image: "https://media.base44.com/images/public/6a554b016ff6fa6eb6e63b81/0bc09fb3d_Screenshot2026-07-17110424.png" },
  { title: "Clinical trial readiness", category: "Research operations", description: "Trial sites, enrolment and regulated operational capabilities in a single workspace.", image: "https://media.base44.com/images/public/6a554b016ff6fa6eb6e63b81/9abb36f41_MeinoMalawiClinicalTrialDB.png" },
  { title: "Historical analytics", category: "Operational insight", description: "Trends, comparisons and key health events across a selected reporting window.", image: "https://media.base44.com/images/public/6a554b016ff6fa6eb6e63b81/850a2d825_image.png" }
];