"use client";

import { useState } from "react";
import { Check, LockKeyhole, UserRound } from "lucide-react";

export default function DynamicConsentDemo() {
  const [shared, setShared] = useState(false);
  return <section id="dynamic-consent" className="scroll-mt-36 bg-primary py-20 text-primary-foreground"><div className="container-wide grid items-center gap-12 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-teal-300">Dynamic Consent</p><h2 className="mt-3 font-display text-3xl font-bold md:text-5xl">Permission that evolves with people</h2><p className="mt-5 max-w-xl text-lg leading-relaxed text-slate-300">A simple illustration of how a person can consider a request and update access. Production access always follows the applicable consent, role, and governance controls.</p></div><div className="rounded-3xl bg-white p-6 text-navy-900 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-teal-600">Patient choice</p><h3 className="mt-1 font-heading text-lg font-bold">Research access request</h3></div><UserRound className="h-8 w-8 text-teal-600"/></div><div className="mt-6 rounded-2xl bg-slate-50 p-4"><p className="text-sm font-semibold">Population health research team</p><p className="mt-1 text-sm text-slate-500">Requests consent-governed use of approved information.</p></div><button onClick={() => setShared(!shared)} className={`mt-5 flex w-full items-center justify-between rounded-xl p-4 text-left text-sm font-bold transition-colors ${shared ? "bg-teal-50 text-teal-800" : "bg-slate-100 text-slate-700"}`}><span>{shared ? "Permission approved" : "Approve permission"}</span><span className={`flex h-7 w-12 items-center rounded-full p-1 ${shared ? "justify-end bg-teal-500" : "justify-start bg-slate-300"}`}><span className="h-5 w-5 rounded-full bg-white"/></span></button><div className="mt-4 flex items-center gap-2 text-xs text-slate-500"><LockKeyhole className="h-4 w-4"/>{shared ? <><Check className="h-4 w-4 text-teal-600"/> Consent status updated</> : "No access is granted"}</div></div></div></section>;
}
