import { ArrowDown, FileText, ShieldCheck } from "lucide-react";
import TrustBrandMark from "@/components/trust/TrustBrandMark";

export default function TrustHero() {
  return <section id="overview" className="relative overflow-hidden bg-gradient-to-br from-slate-50 via-white to-teal-50 pt-32 pb-20 md:pt-40 md:pb-28">
    <div className="absolute inset-0 overflow-hidden"><div className="absolute -top-24 left-[8%] h-80 w-80 rounded-full bg-teal-200/50 blur-3xl"/><div className="absolute right-[6%] top-14 h-96 w-96 rounded-full bg-lime-100/60 blur-3xl"/><div className="absolute right-[12%] bottom-12 h-28 w-28 rounded-full border-[18px] border-teal-100/70"/></div>
    <div className="container-narrow relative text-center"><TrustBrandMark /><div className="mt-8 inline-flex items-center gap-2 rounded-full bg-primary px-4 py-2 text-xs font-bold uppercase tracking-[0.16em] text-primary-foreground"><ShieldCheck className="h-4 w-4 text-teal-300"/>The LifeHealth Trust Standard</div><h1 className="mx-auto mt-6 max-w-5xl font-display text-4xl font-extrabold tracking-tight text-navy-900 md:text-7xl">Trust Is The Foundation Of LifeHealth</h1><p className="mx-auto mt-7 max-w-3xl text-lg leading-relaxed text-slate-600 md:text-xl">LifeHealth was built on a simple belief: people should own, understand, control, and benefit from their health information. Every product, AI capability, and partnership begins with trust.</p><div className="mt-10 flex flex-wrap justify-center gap-3"><a href="#13-trust-principles" className="inline-flex items-center gap-2 rounded-xl bg-primary px-6 py-3.5 text-sm font-bold text-primary-foreground shadow-lg shadow-navy-900/20 transition-transform hover:-translate-y-0.5"><ArrowDown className="h-4 w-4"/>Explore The 13 Principles</a><a href="#trust-documents" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-6 py-3.5 text-sm font-bold text-navy-900 shadow-sm transition-colors hover:bg-teal-50"><FileText className="h-4 w-4 text-teal-600"/>Trust Documents</a></div></div>
  </section>;
}
